[package]
name = "ringhopper"
authors = ["Snowy Mouse"]
version = "0.1.0"
description = "Library for modding Halo: Combat Evolved"
license = "GPL-3.0-only"

[lib]
name = "ringhopper"
doc = true

[dependencies]
encoding = "0.2"
rat-in-a-tube = "0.2.0"
texpresso = "2.0"

strings = { path = "../strings", package = "ringhopper-strings" }
macros = { path = "../macros", package = "ringhopper-macros" }
h1_code_generator = { path = "src/engines/h1/definitions/h1_code_generator" }
h1_engine_target_codegen = { path = "src/engines/h1/engine_target/h1_engine_target_codegen" }

[dev-dependencies]
tiff = "0.7"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.40"
features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem"
]
