[package]
name = "h1_code_generator"
version = "0.1.0"
description = "Code generator"
license = "GPL-3.0-only"

[lib]
doc = false
proc-macro = true

[dependencies]
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
