[package]
name = "invader"
version = "0.1.0"
description = "The free Halo: Combat Evolved modding toolkit"
license = "GPL-3.0-only"

[lib]
name = "invader"
doc = true

[dependencies]
strings = { path = "../strings" }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.39"
features = [
    "Win32_Foundation",
    "Win32_System_Console"
]
