[package]
name = "invader"
authors = ["Snowy Mouse"]
version = "0.1.0"
autobins = false
description = "The free Halo: Combat Evolved modding toolkit"
license = "GPL-3.0-only"
build = "build.rs"

[dependencies]
ringhopper = { path = "../ringhopper" }
macros = { path = "../macros", package = "ringhopper-macros" }
strings = { path = "../strings", package = "ringhopper-strings" }
encoding = "0.2"
tiff = "0.7"
png = "0.17"
flate2 = "1.0"

[[bin]]
name = "invader"
path = "src/main.rs"
doc = false

[build-dependencies]
embed-resource = "1.7"
