[package]
name = "invader"
version = "0.1.0"
description = "The free Halo: Combat Evolved modding toolkit"
license = "GPL-3.0-only"

[lib]
name = "invader"
doc = true

[dependencies]
strings = { path = "../strings" }
