[package]
name = "invader"
version = "0.1.0"
autobins = false
description = "The free Halo: Combat Evolved modding toolkit"
license = "GPL-3.0-only"
build = "build.rs"

[dependencies]
ringhopper = { path = "../ringhopper" }
macros = { path = "../macros" }
strings = { path = "../strings" }
encoding = "0.2"

[[bin]]
name = "invader"
path = "src/main.rs"
doc = false

[build-dependencies]
embed-resource = "1.7"
