[package]
name = "invader"
authors = ["Snowy Mouse"]
version = "0.1.0"
autobins = false
description = "The free Halo: Combat Evolved modding toolkit"
license = "GPL-3.0-only"
build = "build.rs"
repository = "https://git.sr.ht/~snowymouse/invader"
publish = false

[dependencies]
ringhopper = { path = "../ringhopper" }
macros = { path = "macros", package = "ringhopper-macros" }
ringhopper-proc = { path = "../ringhopper/proc", package = "ringhopper-proc" }
encoding = "0.2"
tiff = "0.7"
png = "0.17"
flate2 = "1.0"
rubato = "0.12"
vorbis_rs = "0.1"
symphonia = { version = "0.5.1", features = ["wav", "flac", "pcm"], default-features = false }
xbadpcm = "0.1"
libsamplerate-sys = "0.1.12"

[[bin]]
name = "invader"
path = "src/main.rs"
doc = false

[build-dependencies]
embed-resource = "1.7"
