//! Halo: Combat Evolved tag definitions.

extern crate h1_code_generator;
use self::h1_code_generator::load_json_def;
use crate::engines::h1::{TagSerialize, TagSerializeSwapped, TagReference, ScenarioScriptNodeValue, Index, TagID, Pointer};

use crate::error::*;
use crate::types::*;
use crate::types::tag::{TagBlockFn, TagField};

load_json_def!("actor.json");
load_json_def!("actor_variant.json");
load_json_def!("antenna.json");
load_json_def!("biped.json");
load_json_def!("bitfield.json");
load_json_def!("bitmap.json");
load_json_def!("camera_track.json");
load_json_def!("color_table.json");
load_json_def!("continuous_damage_effect.json");
load_json_def!("contrail.json");
load_json_def!("damage_effect.json");
load_json_def!("decal.json");
load_json_def!("detail_object_collection.json");
load_json_def!("device_control.json");
load_json_def!("device.json");
load_json_def!("device_light_fixture.json");
load_json_def!("device_machine.json");
load_json_def!("dialogue.json");
load_json_def!("effect.json");
load_json_def!("enum.json");
load_json_def!("equipment.json");
load_json_def!("flag.json");
load_json_def!("fog.json");
load_json_def!("font.json");
load_json_def!("garbage.json");
load_json_def!("gbxmodel.json");
load_json_def!("globals.json");
load_json_def!("glow.json");
load_json_def!("grenade_hud_interface.json");
load_json_def!("hud_globals.json");
load_json_def!("hud_interface_types.json");
load_json_def!("hud_message_text.json");
load_json_def!("hud_number.json");
load_json_def!("input_device_defaults.json");
load_json_def!("item_collection.json");
load_json_def!("item.json");
load_json_def!("lens_flare.json");
load_json_def!("light.json");
load_json_def!("lightning.json");
load_json_def!("light_volume.json");
load_json_def!("material_effects.json");
load_json_def!("meter.json");
load_json_def!("model_animations.json");
load_json_def!("model_collision_geometry.json");
load_json_def!("model.json");
load_json_def!("multiplayer_scenario_description.json");
load_json_def!("object.json");
load_json_def!("particle.json");
load_json_def!("particle_system.json");
load_json_def!("physics.json");
load_json_def!("placeholder.json");
load_json_def!("point_physics.json");
load_json_def!("preferences_network_game.json");
load_json_def!("projectile.json");
load_json_def!("scenario.json");
load_json_def!("scenario_structure_bsp.json");
load_json_def!("scenery.json");
load_json_def!("shader_environment.json");
load_json_def!("shader.json");
load_json_def!("shader_model.json");
load_json_def!("shader_transparent_chicago_extended.json");
load_json_def!("shader_transparent_chicago.json");
load_json_def!("shader_transparent_generic.json");
load_json_def!("shader_transparent_glass.json");
load_json_def!("shader_transparent_meter.json");
load_json_def!("shader_transparent_plasma.json");
load_json_def!("shader_transparent_water.json");
load_json_def!("sky.json");
load_json_def!("sound_environment.json");
load_json_def!("sound.json");
load_json_def!("sound_looping.json");
load_json_def!("sound_scenery.json");
load_json_def!("string_list.json");
load_json_def!("tag_collection.json");
load_json_def!("ui_widget_definition.json");
load_json_def!("unicode_string_list.json");
load_json_def!("unit_hud_interface.json");
load_json_def!("unit.json");
load_json_def!("vehicle.json");
load_json_def!("virtual_keyboard.json");
load_json_def!("weapon_hud_interface.json");
load_json_def!("weapon.json");
load_json_def!("weather_particle_system.json");
load_json_def!("wind.json");
